- id: cblack
  name: cblack
  description: "Black: The uncompromising Python code formatter - 2 space indent fork"
  entry: cblack --check
  language: python
  language_version: python3
  require_serial: true
  types: [python]

